trigger:
  branches:
    include:
      - main  # Déclenche la pipeline pour les commits dans la branche 'main'

pool: Pooltest

variables:
  terraformVersion: '1.9.8'  # Version de Terraform

steps:

  # Étape 1 : Cloner le dépôt GitHub
  - checkout: self  # Syntaxe simplifiée pour le checkout
    displayName: 'Checkout code'

  # Étape 5 : Vérifier le plan Terraform
  - script: |
      terraform plan -out=tfplan || exit 1
    displayName: 'Terraform Plan'

  # Étape 6 : Appliquer le plan Terraform
  - script: |
      terraform apply -auto-approve tfplan || exit 1
    displayName: 'Terraform Apply'

  # Étape 7 : Vérifier le contenu des artefacts avant publication
  - script: |
      echo "Checking for Terraform artifacts"
      ls -la $(Build.ArtifactStagingDirectory)
    displayName: 'Check Artifacts'